FROM node:22-alpine AS builder

WORKDIR /app

COPY backend/package*.json ./backend/
COPY shared/ ./shared/

WORKDIR /app/backend
RUN npm ci

COPY backend/ .

RUN npm run build

# Runtime stage
FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/backend/package*.json ./
COPY --from=builder /app/backend/node_modules ./node_modules

COPY --from=builder /app/backend/dist ./dist

COPY backend/src ./src

ENV PORT=4000
EXPOSE 4000

CMD ["npm", "start"]